import React, { useState } from 'react'
import '../styles/glass.css'

export default function GameRules() {
    const [isExpanded, setIsExpanded] = useState(false)

    return (
        <div className="glass-panel" style={{
            padding: '20px',
            marginBottom: '20px',
            cursor: 'pointer',
            transition: 'all 0.3s ease'
        }}
            onClick={() => setIsExpanded(!isExpanded)}
        >
            <div style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: isExpanded ? '20px' : '0'
            }}>
                <h3 style={{ fontSize: '1.3rem', margin: 0 }}>
                    📖 遊戲規則 Game Rules
                </h3>
                <span style={{ fontSize: '1.5rem', transition: 'transform 0.3s', transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)' }}>
                    ▼
                </span>
            </div>

            {isExpanded && (
                <div style={{
                    animation: 'fadeIn 0.3s ease',
                    fontSize: '0.95rem',
                    lineHeight: '1.6'
                }}>
                    <div style={{ marginBottom: '15px' }}>
                        <h4 style={{ color: 'var(--color-yellow)', marginBottom: '8px' }}>
                            目標 Objective
                        </h4>
                        <p>猜出電腦隨機生成的秘密數字（無重複數字）</p>
                        <p style={{ fontSize: '0.85rem', opacity: 0.8 }}>
                            Guess the secret number generated by computer (no duplicate digits)
                        </p>
                    </div>

                    <div style={{ marginBottom: '15px' }}>
                        <h4 style={{ color: 'var(--color-yellow)', marginBottom: '8px' }}>
                            規則說明 Rules
                        </h4>
                        <ul style={{ paddingLeft: '20px', margin: '10px 0' }}>
                            <li style={{ marginBottom: '8px' }}>
                                <strong>A</strong> = 數字和位置都正確 (Correct digit in correct position)
                            </li>
                            <li style={{ marginBottom: '8px' }}>
                                <strong>B</strong> = 數字正確但位置錯誤 (Correct digit in wrong position)
                            </li>
                            <li>
                                沒有顯示 = 該數字不在秘密數字中 (Digit not in secret number)
                            </li>
                        </ul>
                    </div>

                    <div style={{
                        background: 'rgba(255,209,80,0.1)',
                        padding: '15px',
                        borderRadius: '8px',
                        borderLeft: '4px solid var(--color-yellow)'
                    }}>
                        <h4 style={{ color: 'var(--color-yellow)', marginBottom: '10px' }}>
                            範例 Example (秘密數字 Secret: 2489)
                        </h4>
                        <div style={{ fontFamily: 'monospace', fontSize: '1.1rem' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid rgba(255,255,255,0.1)' }}>
                                <span>猜測 Guess: <strong>2345</strong></span>
                                <span style={{ color: 'var(--color-pink)' }}>結果 Result: <strong>1A1B</strong></span>
                            </div>
                            <div style={{ fontSize: '0.85rem', marginTop: '10px', opacity: 0.9 }}>
                                <p>• <strong>2</strong> 在正確位置 (position 1) → <strong>1A</strong></p>
                                <p>• <strong>4</strong> 存在但位置錯誤 (should be position 3) → <strong>1B</strong></p>
                                <p>• <strong>3, 5</strong> 不在秘密數字中 → 無顯示</p>
                            </div>
                        </div>

                        <div style={{ fontFamily: 'monospace', fontSize: '1.1rem', marginTop: '15px' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid rgba(255,255,255,0.1)' }}>
                                <span>猜測 Guess: <strong>2489</strong></span>
                                <span style={{ color: 'var(--color-yellow)' }}>結果 Result: <strong>4A0B</strong></span>
                            </div>
                            <div style={{ fontSize: '0.85rem', marginTop: '10px', opacity: 0.9 }}>
                                <p>✅ 完全正確！All correct! 遊戲勝利 You win!</p>
                            </div>
                        </div>
                    </div>

                    <div style={{ marginTop: '15px', fontSize: '0.85rem', opacity: 0.7, textAlign: 'center' }}>
                        點擊此區域收起規則 Click to collapse rules
                    </div>
                </div>
            )}

            <style>{`
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(-10px); }
          to { opacity: 1; transform: translateY(0); }
        }
      `}</style>
        </div>
    )
}
